url: https://etoews.github.io
author: Everett Toews
description: Helping you shave narwhals
title: etoews
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "page:num"
twitter:
  username: etoews
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
